apiVersion: v1
kind: ReplicationController
metadata:
  name: admin-fe
  labels:
    name: admin-fe
spec:
  replicas: 1
  selector:
    name: admin-fe
  template:
    metadata:
      labels:
        name: admin-fe
    spec:
      containers:
      - name: pet
        image: wso2mss/petstore-admin-fe
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 8080
