apiVersion: v1
kind: ReplicationController
metadata:
  name: store-fe
  labels:
    name: store-fe
spec:
  replicas: 1
  selector:
    name: store-fe
  template:
    metadata:
      labels:
        name: store-fe
    spec:
      containers:
      - name: store-fe
        image: wso2mss/petstore-store-fe
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: FE_FILE_SERVICE_HOST
          value: fileserver
        - name: FE_FILE_SERVICE_PORT
          value: "80"
        - name: FE_PET_SERVICE_HOST
          value: pet
        - name: FE_PET_SERVICE_PORT
          value: "80"
        - name: FE_USER_SERVICE_HOST
          value: security
        - name: FE_USER_SERVICE_PORT
          value: "80"
        - name: FE_TXN_SERVICE_HOST
          value: security
        - name: FE_TXN_SERVICE_PORT
          value: "80"
        - name: FE_FILE_SERVER_NODE_PORT
          value: "31111"
        ports:
        - containerPort: 8080
