apiVersion: v1
kind: ReplicationController
metadata:
  name: fileserver
  labels:
    name: fileserver
spec:
  replicas: 1
  selector:
    name: fileserver
  template:
    metadata:
      labels:
        name: fileserver
    spec: 
      containers: 
        - resources:
          image: wso2msf4j/petstore-fileserver
          name: fileserver
          env:
          - name: GET_HOSTS_FROM
            value: dns
          ports: 
            - containerPort: 8080
              name: fileserver
          volumeMounts:
              # name must match the volume name below
            - name: fileserver-persistent-storage
              # mount path within the container
              mountPath: /var/www/html/upload
      volumes:
        - name: fileserver-persistent-storage
          hostPath:
             path: /home/core/fileserver
      nodeSelector:
        disktype: ssd
